# Generated by Django 5.0.6 on 2026-05-16 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('api_keys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='api_keys.apikey'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyusage',
            index=models.Index(fields=['user', 'date'], name='analytics_d_user_id_cce9ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyusage',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uniq_daily_usage_per_user_per_day'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['user', 'created_at'], name='analytics_r_user_id_7c1660_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['api_key', 'created_at'], name='analytics_r_api_key_4f1784_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['status_code'], name='analytics_r_status__1d1e26_idx'),
        ),
    ]
